[package]
name = "merkle_poseidon_root_ecdsa_test"
type = "bin"
authors = [""]

[dependencies]
poseidon = { tag = "v0.2.2", git = "https://github.com/noir-lang/poseidon" }
sha256 = { tag = "v0.3.0", git = "https://github.com/noir-lang/sha256" }
